### ISSUE TITLE
Troubleshooting Django Ticket 10070

### ISSUE THREAD

**Issue by ryancheley** [ryancheley/public-notes#1]
[Django Ticket 10070](https://code.djangoproject.com/ticket/10070) reports an issue "Named parameters not working on raw sql queries with sqlite"

This is my attempt to try and figure out what is going on.

Side note: I initially marked this ticket as done at Django Con US 2022 as it seemed to no longer be a bug based on review of test methods, but about a week after it was closed, it was re-opened and shown to be reproducible.

**Comment by ryancheley** [comment]
Steps to reproduce:

First, let's look at a non-SQLite database and see what happens

```python

>>> from django.db import connection
>>> c = connection.cursor()
>>> c.execute("select app_label from django_content_type where id = 1")
>>> c.execute("select app_label from django_content_type where id = %(id)s", {'id':'1'})

```

This runs without error. 

Now, let's try with connection to a SQLite database

```python

>>> from django.db import connection
>>> c = connection.cursor()
>>> c.execute("select app_label from django_content_type where id = 1")
>>> c.execute("select app_label from django_content_type where id = %(id)s", {'id':'1'})

```

And we now get this:

```bash
Traceback (most recent call last):
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "%": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "%": syntax error

```

**Comment by ryancheley** [comment]
The second to the last line of the stack trace says

```bash
File "/Users/ryan/PycharmProjects/tatisjr/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
```

So let's start there!

**Comment by ryancheley** [comment]
We'll investigate `django.db.backends.sqlite3.base` and look at the `SQLiteCursorWrapper` class

Here, we see the `execute` method does this

```python
    def execute(self, query, params=None):
        if params is None:
            return Database.Cursor.execute(self, query)
        query = self.convert_query(query)
        return Database.Cursor.execute(self, query, params)

```

This means that IF there is a parameter on the `query` it will use the method `self.convert_query `. Let's take a look at this

```python
    def convert_query(self, query):
        return FORMAT_QMARK_REGEX.sub("?", query).replace("%%", "%")
```

**Comment by ryancheley** [comment]
This in turn just returns `FORMAT_QMARK_REGEX` which is defined as

```python
FORMAT_QMARK_REGEX = _lazy_re_compile(r"(?<!%)%s")
```

and `_lazy_re_compile` is from `from django.utils.regex_helper import _lazy_re_compile`

Looking at the source code for that helper function 

```python
def _lazy_re_compile(regex, flags=0):
    """Lazily compile a regex with flags."""

    def _compile():
        # Compile the regex if it was not passed pre-compiled.
        if isinstance(regex, (str, bytes)):
            return re.compile(regex, flags)
        else:
            assert not flags, "flags must be empty if regex is passed pre-compiled"
            return regex

    return SimpleLazyObject(_compile)
```

So it looks like it's checking to see if the regex is pre-compiled, and if it is it's saying don't use any flags, but if it's not pre-compiled you can use flags. Either way, it's returning `SimpleLazyObject` object type which is defined in `django.utils.functional`

**Comment by ryancheley** [comment]
`SimpleLazyObject` is 

```python
    """
    A lazy object initialized from any function.

    Designed for compound objects of unknown type. For builtins or objects of
    known type, use django.utils.functional.lazy.
    """
```

It subclasses `LazyObject` which itself is

```python
    """
    A wrapper for another class that can be used to delay instantiation of the
    wrapped class.

    By subclassing, you have the opportunity to intercept and alter the
    instantiation. If you don't need to do that, use SimpleLazyObject.
    """
```

**Comment by ryancheley** [comment]
OK ... so now I think I *really* understand the issue. 

This all goes back to the `raw()` method on the object manager. 🤦🏻‍♂️

The basic problem is that IF I were to write something like

```python
for i in InjuredList.objects.raw("select * from content_injuredlist where id =  %(id)s", {'id': '1'}):
    print(i)
```

in SQLite I get the error (as stated above) but if I do that in Postgres I don't.

**Comment by ryancheley** [comment]
Further, the fundamental issue is that the way the query is being passed 

```
select * from content_injuredlist where id =  %(id)s", {'id': '1'}
```

Is the real problem because SQLite doesn't like that particular implementation. If you instead do

```
select * from content_injuredlist where id = :id", {'id': '1'}
```

It returns fine.

SO ... what needs to be done is to somehow transform the first string into the second, accounting for all of the ways that someone could put in a parameter set.

**Comment by ryancheley** [comment]
This will work in the simplest case:

```python
re.sub("\)s", "",  re.sub("%\(", ":", query))
```

Still need to verify for more than one parameter

**Comment by ryancheley** [comment]
I've been able to manually verify that this will do what is needed. Now I need to determine how to update the needed methods, write tests, and submit PR

**Comment by ryancheley** [comment]
Wrote up my condensed findings in the ticket [here](https://code.djangoproject.com/ticket/10070#comment:27)

**Comment by ryancheley** [comment]
OK, as I work through testing the issue I've found a few things:

1. There is a features file `django.db.backends.sqlite3.features` which has a `DatabaseFeatures` class with `supports_paramstyle_pyformat` value set to `False`
2. `tests.raw_query.tests` has a class called `RawQueryTests` that has two methods 
    - `test_pyformat_params`
    - `test_query_representation`

So, in order for the tests to check what is happening it looks like I have to:

1. Add the code above
2. Change the flag for `supports_paramstyle_pyformat`

**Comment by ryancheley** [comment]
This means that there are 4 potential states to check to make sure that I'm thinking about this correctly:

- [x] The original state where my code is NOT added AND the flag is set to `False`. This should pass AND one test should be skipped
- [x] The original state where my code is NOT added AND the flag is set to `True`. This should fail on the test `test_pyformat_params`
- [x] The updated state where my code IS added AND the flag is set to `False`. This should pass AND one test should be skipped
- [x] The updated state where my code IS added AND the flag is set to `True`. This should pass on both tests

The command I'm running to check the tests is

```bash
./runtests.py -k test_pyformat_params -k test_query_representation
```

**Comment by ryancheley** [comment]
First item did as expected

> The original state where my code is NOT added AND the flag is set to `False`. This should pass AND one test should be skipped

output was

```bash
Testing against Django installed in '/Users/ryan/github/django/django' with up to 8 processes
Found 2 test(s).
Creating test database for alias 'default'...
System check identified no issues (17 silenced).
s.
----------------------------------------------------------------------
Ran 2 tests in 0.028s
```

**Comment by ryancheley** [comment]
Second item did as expected

> The original state where my code is NOT added AND the flag is set to `True`. This should fail on the test `test_pyformat_params`

```bash
Testing against Django installed in '/Users/ryan/github/django/django' with up to 8 processes
Found 2 test(s).
Creating test database for alias 'default'...
System check identified no issues (17 silenced).
E.
======================================================================
ERROR: test_pyformat_params (raw_query.tests.RawQueryTests)
Test passing optional query parameters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryan/github/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/ryan/github/django/django/db/backends/sqlite3/base.py", line 370, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "%": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryan/github/django/django/test/testcases.py", line 1604, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/Users/ryan/github/django/tests/raw_query/tests.py", line 240, in test_pyformat_params
    results = list(qset)
  File "/Users/ryan/github/django/django/db/models/query.py", line 2085, in __len__
    self._fetch_all()
  File "/Users/ryan/github/django/django/db/models/query.py", line 2080, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/ryan/github/django/django/db/models/query.py", line 2107, in iterator
    yield from RawModelIterable(self)
  File "/Users/ryan/github/django/django/db/models/query.py", line 154, in __iter__
    query_iterator = iter(query)
  File "/Users/ryan/github/django/django/db/models/sql/query.py", line 112, in __iter__
    self._execute_query()
  File "/Users/ryan/github/django/django/db/models/sql/query.py", line 152, in _execute_query
    self.cursor.execute(self.sql, params)
  File "/Users/ryan/github/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/ryan/github/django/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ryan/github/django/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/ryan/github/django/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ryan/github/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/ryan/github/django/django/db/backends/sqlite3/base.py", line 370, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "%": syntax error

----------------------------------------------------------------------
Ran 2 tests in 0.028s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by ryancheley** [comment]
Third item did as expected

> The updated state where my code IS added AND the flag is set to `False`. This should pass AND one test should be skipped

```bash
Testing against Django installed in '/Users/ryan/github/django/django' with up to 8 processes
Found 2 test(s).
Creating test database for alias 'default'...
System check identified no issues (17 silenced).
s.
----------------------------------------------------------------------
Ran 2 tests in 0.022s

OK (skipped=1)
Destroying test database for alias 'default'...
```

**Comment by ryancheley** [comment]
Fourth item 

> The updated state where my code IS added AND the flag is set to True. This should pass on both tests

```bash
Testing against Django installed in '/Users/ryan/github/django/django' with up to 8 processes
Found 2 test(s).
Creating test database for alias 'default'...
System check identified no issues (17 silenced).
..
----------------------------------------------------------------------
Ran 2 tests in 0.025s

OK
Destroying test database for alias 'default'...
```

**Comment by ryancheley** [comment]
OK ... now we have an new line of code that fixes the bug, and passes the tests. Now, let's run the entire test suite to make sure that everything that passed before, passes now!

**Comment by ryancheley** [comment]
The entire test suite passed! 🥳

**Comment by ryancheley** [comment]
PR submitted and feedback provided in comments [28](https://code.djangoproject.com/ticket/10070#comment:28) and [29](https://code.djangoproject.com/ticket/10070#comment:29) that I'll need to look into. 

The regex solution could be fragile (something I hadn't considered!) and so other, more robust, ideas have been put forward. Will look at it next week

**Comment by ryancheley** [comment]
The feedback from Shia seems to point to [this](https://github.com/ryancheley/django/blob/970f61fefb148284fb2af63b5cc844279254111a/django/db/backends/oracle/base.py#L486)

There are some more methods below that that are worth looking into as well

**Comment by ryancheley** [comment]
I decided to implement the idea from [comment 28](https://code.djangoproject.com/ticket/10070#comment:28) (because I understood what it was asking for!)

Next is to make changes to the documentation based on [this PR comment](https://github.com/django/django/pull/16243#pullrequestreview-1161175532) from Simon

**Comment by ryancheley** [comment]
Documentation changes also made with [this commit](https://github.com/django/django/pull/16243/commits/a9dcba4e09760b1dea06e51cff0b631fca4b161c)

**Comment by ryancheley** [comment]
Running full test suite leads to new errors 🤦🏻‍♂️

Now need to investigate why this is failing

```bash
./runtests.py -k test_cursor_executemany_with_pyformat_iterator -k test_cursor_executemany_with_pyformat
```

**Comment by ryancheley** [comment]
Looks like *maybe* the change added doesn't actually support `pyformat`. Will need to look into that more deeply. See [this link](https://pyformat.info) for more details

**Comment by ryancheley** [comment]
> Looks like _maybe_ the change added doesn't actually support `pyformat`. Will need to look into that more deeply. See [this link](https://pyformat.info) for more details

According to[https://stackoverflow.com/a/12184307](this)  StackOverflow answer 

> The underlying library [doesn't support %s](http://sqlite.org/c3ref/bind_blob.html), so it would need to be replaced manually.

looks like I need to change the pyformat support **BACK** to `False`

**Comment by ryancheley** [comment]
Marius correctly pointed out that SQLite does actually support `pyformat` in this [comment](https://github.com/django/django/pull/16243#issuecomment-1300305644) and I'm kind of like 🤦🏻‍♂️ ... yeah, if it DID NOT then the other tests would have failed.

**Comment by ryancheley** [comment]
My general idea (after a couple of hours of banging my head against the wall) is that the `param_list` is a `generator`. I essentially need to take the data from that generator (which yields a dictionary) and do what was done with the `execute` method which looks like this:

```
args = {k: ":%s" % k for k in params}
query %= args
```

The problem is that when I take the `param_list` generator to do something with it I USE UP the generator. So my understanding of how to work with generators is kind of broken maybe

**Comment by ryancheley** [comment]
turns out my idea for generators is correct, it was my implementation that was ‘missing something’. 

The `executemany` method doesn’t CARE what kind of iterable is in the `param_list` if just wants ANY kind of iterable. Once that clicked I realized I could just set the `param_list` to a list comprehension of itself, i.e. 

```python
param_list = [p for p in param_list]
```

this means that my `generator` doesn’t get used up when I pass it to the return at the end of the method. 

It’s small things like this that can be super hard to know, even harder to learn, but are worth the struggle of working through.

**Comment by ryancheley** [comment]
I’ve also discovered that this doesn’t work on Windows

```python
query %= args
```

but it does on Linux OS 🤷🏼‍♂️

**Comment by ryancheley** [comment]
> I’ve also discovered that this doesn’t work on Windows
> 
> ```python
> query %= args
> ```
> 
> but it does on Linux OS 🤷🏼‍♂️

So this is wrong. It's not an issue with Windows ... the tests were failing on my Mac as well, but I just didn't see it locally when I ran the tests and I'm not really sure why.

**Comment by ryancheley** [comment]
OK, here is the list of tests that fail locally

- ERROR: test_database_queried (backends.base.test_base.ExecuteWrapperTests)
- ERROR: test_nested_wrapper_invoked (backends.base.test_base.ExecuteWrapperTests)
- ERROR: test_wrapper_invoked_many (backends.base.test_base.ExecuteWrapperTests)
- ERROR: test_cursor_executemany (backends.tests.BackendTestCase)
- ERROR: test_cursor_executemany_with_empty_params_list (backends.tests.BackendTestCase)
- ERROR: test_cursor_executemany_with_iterator (backends.tests.BackendTestCase)
- ERROR: test_queries (backends.tests.BackendTestCase)

This is due to (mostly) a `}` being passed in during to parameters BECAUSE I'm assuming all of the `param_list` are iterables and it seems that I can't assume that.

**Comment by ryancheley** [comment]
I'll try to figure it out one at a time and and work through this.

**Comment by ryancheley** [comment]
The code has been updated and it **seems** to work (there is a test that randomly fails when the entire test suite is run, but not when run individually (`test_database_sharing_in_threads`) or are all the way up to running all of the backend tests (currently 394 of them)

Also, the code is ugly … but it works!

**Comment by ryancheley** [comment]
PR was reviewed by several people and even a [PR](https://github.com/ryancheley/django/pull/1) on my PR for improvements to the code! Super helpful to see how others would handle the code that needed to be written. I've not had a chance to *really* review it yet (just a cursory glance) but WOW this is awesome 😀

**Comment by ryancheley** [comment]
OK ... just reviewed the codes and SO many things that just 🤯

In the `execute` method can have this

```python
if hasattr(params, "keys"):
             args = {k: ":%s" % k for k in params}
             query = query % args
```

be replaced with this:

```python
names = list(params) if isinstance(params, Mapping) else None
```

**Comment by ryancheley** [comment]
In the `executemany()` there is the use of a walrus operator ( `:=` ). I did confirm that Django 4.1 only supports Python 3.8+ and since the walrus operator was introduced in 3.8 so that's good.

**Comment by ryancheley** [comment]
The PR passed all of tests! Added bonus, this particular issue with help from ngnpope also lead to a [PR](https://github.com/python/cpython/pull/99078) to update in the Python documentation

**Comment by ryancheley** [comment]
Holy crap … the change was [merged](https://github.com/django/django/pull/16243#event-7762186709) today by Mariusz Felisiak

**Comment by ryancheley** [comment]
Since it was [merged](https://github.com/django/django/commit/8e6ea1d153a852b83eaa4807301b143df1647a44), I'm marking as done 😀 🎉
