### ISSUE TITLE
Upgrade DO servers to newer version of Ubuntu 

### ISSUE THREAD

**Issue by ryancheley** [ryancheley/public-notes#2]
Currently the servers, both PROD and UAT are running version 18.04. These are [EOL in April 2023](https://ubuntu.com/about/release-cycle)

**Comment by ryancheley** [comment]
There are notes I’ve taken over the course of the last year(ish) and I’m putting them here for completeness (they had been stored in the Drafts app previously)

## Note 1 - 12/26/2021 8:18AM

Additional ssh is running on port 1022 for uat-test fiddle server

Select the defaults as you go through the upgrade process. 

Upgrade started at 16:25(ish)

When asked to stop services, say yes
When asked to restart services, say yes

Special Notes:

- stop psql before starting upgrade

## Note 2  - 12/26/2021 8:18AM

```bash
sudo apt update
sudo apt list --upgradable
sudo apt upgrade

sudo reboot

sudo service postgresql stop

sudo apt --purge autoremove

sudo apt install update-manager-core

sudo do-release-upgrade
```

Enter `<y>`

Enter `<Enter>`

Enter `<y>`

Enter `<Enter>`

Enter `<y>`

Wait for a while

Do you want to upgrade glibc? Yes

Restart services w/o asking? Yes

---

```bash
Traceback (most recent call last):
  File "/usr/lib/ubuntu-advantage/upgrade_lts_contract.py", line 27, in <module>
    from uaclient.cli import setup_logging
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 22, in <module>
    from uaclient import (
  File "/usr/lib/python3/dist-packages/uaclient/security_status.py", line 4, in <module>
    from apt import Cache  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.6.0: cannot open shared object file: No such file or directory
```
## Note 3 - 12/26/2021 8:18AM

Upgrade might be an issue with the python path

See [here](https://askubuntu.com/questions/1336425/no-module-named-uaclient-during-sudo-apt-upgrade-ubuntu-16-04)

## Note 4 - 12/27/2021 5:00PM

https://stackoverflow.com/questions/13708180/python-dev-installation-error-importerror-no-module-named-apt-pkg

```bash
sudo apt-get install python3-apt --reinstall
```

May need to do this though:

```bash
cd /usr/lib/python3/dist-packages
sudo ln -s apt_pkg.cpython-{your-version-number}-x86_64-linux-gnu.so apt_pkg.so

sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so

apt_pkg.cpython-36m-x86_64-linux-gnu.so
```


```bash
Traceback (most recent call last):
  File "/usr/lib/ubuntu-advantage/upgrade_lts_contract.py", line 27, in <module>
    from uaclient.cli import setup_logging
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 22, in <module>
    from uaclient import (
  File "/usr/lib/python3/dist-packages/uaclient/security_status.py", line 4, in <module>
    from apt import Cache  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.6.0: cannot open shared object file: No such file or directory
```
Upgrade complete 

The upgrade has completed but there were errors during the upgrade 
process. 

## Note 5 - 12/28/2021 6:45AM

Remove the deadsnakesppa before upgrading

```bash
add-apt-repository --remove ppa:deadsnakes/ppa -y
```

https://www.cyberciti.biz/faq/upgrade-ubuntu-18-04-to-20-04-lts-using-command-line/

```bash
 libpython3.6-stdlib:amd64
 python3-pil:amd64
 python3.6
 python3-apt
 install-info
 gpgconf
 gnupg
 python3.6-venv
 gpg-agent
 gpg-wks-server
 gpg-wks-client
 libpython3.6-dev:amd64
 gpgsm
 systemd
 postgresql-common
 gnupg-utils
 python3.6-dev
 dirmngr
 gpg
 libpython3.6:amd64
 libnss-systemd:amd64
 libpam-systemd:amd64
 systemd-sysv
 snapd
 udev
 friendly-recovery
 initramfs-tools-core
 initramfs-tools
Traceback (most recent call last):
  File "/usr/lib/ubuntu-advantage/upgrade_lts_contract.py", line 27, in <module>
    from uaclient.cli import setup_logging
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 22, in <module>
    from uaclient import (
  File "/usr/lib/python3/dist-packages/uaclient/security_status.py", line 4, in <module>
    from apt import Cache  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.6.0: cannot open shared object file: No such file or directory

Upgrade complete

The upgrade has completed but there were errors during the upgrade
process.

To continue please press [ENTER]
```


Check [here](ImportError: libapt-pkg.so.6.0: cannot open shared object file: No such file or directory) which indicates the answer is:

```bash
sudo apt install libglu1
apt upgrade
PYTHONPATH=/usr/lib/python3/dist-packages/ apt upgrade
sudo do-release-upgrade
```

Try [this](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1954542)

## Note 6 - 4/24/2022 11:42AM

When trying to update and upgrade an error is generated. The fix for it is [here](https://askubuntu.com/a/1403604)

```bash
sudo dpkg -i --force-all /var/cache/apt/archives/libpython3.9-stdlib_3.9.12-1+bionic2_amd64.deb

sudo dpkg -i --force-all /var/cache/apt/archives/libpython3.9-minimal_3.9.12-1+bionic2_amd64.deb
```

Upgrade instructions [here](https://linuxconfig.org/how-to-upgrade-ubuntu-to-22-04-lts-jammy-jellyfish)

However, this [post](https://www.digitalocean.com/community/questions/can-t-upgrade-from-18-04-lts-to-20-04-lts) has this command

```bash
sudo RELEASE_UPGRADER_ALLOW_THIRD_PARTY=1 do-release-upgrade
```

Do you want to upgrade glibc now? Yes

Restart Services during upgrade without asking? Yes

**Comment by ryancheley** [comment]
Turns out that the best/only way forward on this was to create new DO droplets for UAT and PROD and then migrate everything over. I’ve done this for UAT and am working on it for PROD next. I’m currently working on a script which will output another script that sets up the sites on PROD so I don’t have to do them one at a time in an artisanal fashion.
